

* harpie

[[https://hackage.haskell.org/package/harpie][file:https://img.shields.io/hackage/v/harpie.svg
]][[https://github.com/tonyday567/harry/actions?query=workflow%3Ahaskell-ci][file:https://github.com/tonyday567/harpie/workflows/haskell-ci/badge.svg]]

* Imports

#+begin_src haskell-ng :results output
:r
:set -Wno-name-shadowing
:set -Wno-type-defaults
:set -XDataKinds
import qualified Harpie.Shape as S
import qualified Harpie.Fixed as F
impot qualified Harpie.Array as A
import Prettyprinter
import GHC.TypeNats
import Data.Vector qualified as V
a = F.range @[2,3,4]
pretty a
e = F.array @[3,3] @Double [4,12,-16,12,37,-43,-16,-43,98]
pretty e
l = F.chol e
pretty l
#+end_src

#+RESULTS:
#+begin_example
Configuration is affected by the following files:
- cabal.project
- cabal.project.local
Build profile: -w ghc-9.12.2 -O1
In order, the following will be built (use -v for more details):
 - harpie-0.1.3.0 (interactive) (lib) (first run)
Preprocessing library for harpie-0.1.3.0...
GHCi, version 9.12.2: https://www.haskell.org/ghc/  :? for help
<no location info>: warning: [GHC-32850] [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules for ‘harpie-0.1.3.0-inplace’ :
        Harpie.Array Harpie.Shape Harpie.Sort

[1 of 4] Compiling Harpie.Shape     ( src/Harpie/Shape.hs, interpreted )
[2 of 4] Compiling Harpie.Sort      ( src/Harpie/Sort.hs, interpreted )
[3 of 4] Compiling Harpie.Array     ( src/Harpie/Array.hs, interpreted )
[4 of 4] Compiling Harpie.Fixed     ( src/Harpie/Fixed.hs, interpreted )
Ok, four modules loaded.
4
Loaded GHCi configuration from /Users/tonyday567/haskell/harpie/.ghci
[1 of 4] Compiling Harpie.Shape     ( src/Harpie/Shape.hs, interpreted )
[2 of 4] Compiling Harpie.Sort      ( src/Harpie/Sort.hs, interpreted )
[3 of 4] Compiling Harpie.Array     ( src/Harpie/Array.hs, interpreted )
[4 of 4] Compiling Harpie.Fixed     ( src/Harpie/Fixed.hs, interpreted )
Ok, four modules loaded.
Ok, four modules reloaded.
<interactive>:7:17: error: [GHC-76037]
    Not in scope: data constructor ‘Harpie.Array’
    Note: No module named ‘Harpie’ is imported.
[[[0,1,2,3],
  [4,5,6,7],
  [8,9,10,11]],
 [[12,13,14,15],
  [16,17,18,19],
  [20,21,22,23]]]
[[4.0,12.0,-16.0],
 [12.0,37.0,-43.0],
 [-16.0,-43.0,98.0]]
[[2.0,0.0,0.0],
 [6.0,1.0,0.0],
 [-8.0,5.0,3.0]]
#+end_example

* chol

#+begin_src haskell-ng :results output
ll = F.expand (*) l l
F.shape ll
pretty ll
#+end_src

#+RESULTS:
#+begin_example
[3,3,3,3]
[[[[4.0,0.0,0.0],
   [12.0,2.0,0.0],
   [-16.0,10.0,6.0]],
  [[0.0,0.0,0.0],
   [0.0,0.0,0.0],
   [-0.0,0.0,0.0]],
  [[0.0,0.0,0.0],
   [0.0,0.0,0.0],
   [-0.0,0.0,0.0]]],
 [[[12.0,0.0,0.0],
   [36.0,6.0,0.0],
   [-48.0,30.0,18.0]],
  [[2.0,0.0,0.0],
   [6.0,1.0,0.0],
   [-8.0,5.0,3.0]],
  [[0.0,0.0,0.0],
   [0.0,0.0,0.0],
   [-0.0,0.0,0.0]]],
 [[[-16.0,-0.0,-0.0],
   [-48.0,-8.0,-0.0],
   [64.0,-40.0,-24.0]],
  [[10.0,0.0,0.0],
   [30.0,5.0,0.0],
   [-40.0,25.0,15.0]],
  [[6.0,0.0,0.0],
   [18.0,3.0,0.0],
   [-24.0,15.0,9.0]]]]
#+end_example


#+begin_src haskell-ng :results output
lla = F.toDynamic ll
-- F.extracts (F.Dims @'[0]) ll
#+end_src

#+RESULTS:
: A.indexes :: Dims -> [Int] -> Array a -> Array a


#+begin_src haskell-ng :results output
A.shape lla
A.index lla [0,0,0,0]
:t A.extracts [0] lla
shape (A.extracts [0] lla)

fmap shape (A.extracts [0] lla)
pretty $ A.extracts [0] lla
#+end_src

#+RESULTS:
: [3,3,3,3]
: 4.0
: A.extracts [0] lla :: Array (Array Double)
: [3]
: UnsafeArray [3] [[3,3,3],[3,3,3],[3,3,3]]
: [UnsafeArray [3,3,3] [4.0,0.0,0.0,12.0,2.0,0.0,-16.0,10.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0],UnsafeArray [3,3,3] [12.0,0.0,0.0,36.0,6.0,0.0,-48.0,30.0,18.0,2.0,0.0,0.0,6.0,1.0,0.0,-8.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0],UnsafeArray [3,3,3] [-16.0,-0.0,-0.0,-48.0,-8.0,-0.0,64.0,-40.0,-24.0,10.0,0.0,0.0,30.0,5.0,0.0,-40.0,25.0,15.0,6.0,0.0,0.0,18.0,3.0,0.0,-24.0,15.0,9.0]]

#+begin_src haskell-ng :results output
:t A.extracts [0] lla
#+end_src

#+RESULTS:
: A.extracts [0] lla :: Array (Array Double)

* expand


#+begin_src haskell-ng :results output
:t expand (,)
#+end_src

#+RESULTS:
: expand (,) :: Array a -> Array b -> Array (a, b)


#+begin_src haskell-ng :results output
a = A.indices [3,3]
pretty a
#+end_src

#+RESULTS:
: [[[0,0],[0,1],[0,2]],
:  [[1,0],[1,1],[1,2]],
:  [[2,0],[2,1],[2,2]]]

#+begin_src haskell-ng :results output
pretty $ fmap pretty $ expand (,) a a
#+end_src

#+RESULTS:
#+begin_example
[[[[([0, 0], [0, 0]),([0, 0], [0, 1]),([0, 0], [0, 2])],
   [([0, 0], [1, 0]),([0, 0], [1, 1]),([0, 0], [1, 2])],
   [([0, 0], [2, 0]),([0, 0], [2, 1]),([0, 0], [2, 2])]],
  [[([0, 1], [0, 0]),([0, 1], [0, 1]),([0, 1], [0, 2])],
   [([0, 1], [1, 0]),([0, 1], [1, 1]),([0, 1], [1, 2])],
   [([0, 1], [2, 0]),([0, 1], [2, 1]),([0, 1], [2, 2])]],
  [[([0, 2], [0, 0]),([0, 2], [0, 1]),([0, 2], [0, 2])],
   [([0, 2], [1, 0]),([0, 2], [1, 1]),([0, 2], [1, 2])],
   [([0, 2], [2, 0]),([0, 2], [2, 1]),([0, 2], [2, 2])]]],
 [[[([1, 0], [0, 0]),([1, 0], [0, 1]),([1, 0], [0, 2])],
   [([1, 0], [1, 0]),([1, 0], [1, 1]),([1, 0], [1, 2])],
   [([1, 0], [2, 0]),([1, 0], [2, 1]),([1, 0], [2, 2])]],
  [[([1, 1], [0, 0]),([1, 1], [0, 1]),([1, 1], [0, 2])],
   [([1, 1], [1, 0]),([1, 1], [1, 1]),([1, 1], [1, 2])],
   [([1, 1], [2, 0]),([1, 1], [2, 1]),([1, 1], [2, 2])]],
  [[([1, 2], [0, 0]),([1, 2], [0, 1]),([1, 2], [0, 2])],
   [([1, 2], [1, 0]),([1, 2], [1, 1]),([1, 2], [1, 2])],
   [([1, 2], [2, 0]),([1, 2], [2, 1]),([1, 2], [2, 2])]]],
 [[[([2, 0], [0, 0]),([2, 0], [0, 1]),([2, 0], [0, 2])],
   [([2, 0], [1, 0]),([2, 0], [1, 1]),([2, 0], [1, 2])],
   [([2, 0], [2, 0]),([2, 0], [2, 1]),([2, 0], [2, 2])]],
  [[([2, 1], [0, 0]),([2, 1], [0, 1]),([2, 1], [0, 2])],
   [([2, 1], [1, 0]),([2, 1], [1, 1]),([2, 1], [1, 2])],
   [([2, 1], [2, 0]),([2, 1], [2, 1]),([2, 1], [2, 2])]],
  [[([2, 2], [0, 0]),([2, 2], [0, 1]),([2, 2], [0, 2])],
   [([2, 2], [1, 0]),([2, 2], [1, 1]),([2, 2], [1, 2])],
   [([2, 2], [2, 0]),([2, 2], [2, 1]),([2, 2], [2, 2])]]]]
#+end_example

#+begin_src haskell-ng :results output
x2 = A.diag $ A.extracts [1,3] (A.expand (,) a a)
:t x2
A.shape x2
fmap A.shape x2
-- vsep $ A.arrayAs (fmap pretty $ x2)
import Data.Bifunctor
:t x2
inds = fmap (fmap (uncurry (<>))) x2
:t S.flatten [3,3]
fl = fmap (fmap (bimap (S.flatten [3,3]) (S.flatten [3,3]))) x2
pretty fl
#+end_src

#+RESULTS:
: x2 :: Array (Array ([Int], [Int]))
: [3]
: UnsafeArray [3] [[3,3],[3,3],[3,3]]
: x2 :: Array (Array ([Int], [Int]))
: S.flatten [3,3] :: [Int] -> Int
: [UnsafeArray [3,3] [(0,0),(0,3),(0,6),(3,0),(3,3),(3,6),(6,0),(6,3),(6,6)],UnsafeArray [3,3] [(1,1),(1,4),(1,7),(4,1),(4,4),(4,7),(7,1),(7,4),(7,7)],UnsafeArray [3,3] [(2,2),(2,5),(2,8),(5,2),(5,5),(5,8),(8,2),(8,5),(8,8)]]

#+begin_src haskell-ng :results output
F.tabulate (F.cross_ (F.range @[3,3])) :: F.Array [3,3] Int
#+end_src

#+RESULTS:
: [0,0,7,0,9,46,0,18,85]

* Next extracts


** Harpie.Array

After an extracts, diag collects together elements where the indices are equal.

 #+begin_src haskell-ng :results output
 a = A.range [3,3]
 ppretty = vsep . arrayAs . fmap pretty
 acc = asArray . scanl (+) (konst [3,3] 0) . arrayAs
 cross a = join . diag . extracts [0,1] . join . acc . drop 0 (-1) . diag . extracts [1,3] $ expand (*) a a
 pretty (cross a)
 #+end_src

 #+RESULTS:
 : [[0,0,0],
 :  [0,9,18],
 :  [7,46,85]]


#+begin_src haskell-ng :results output
e'' = join $ asArray $ scanl (+) (konst [3,3] 0) (arrayAs $ A.drop 0 (-1) e')
join $ diag $ extracts [0,1] e''
#+end_src

#+RESULTS:
: UnsafeArray [3,3] [0,0,0,0,9,18,7,46,85]


*** collect

#+begin_src haskell-ng :results output
:set -Wno-incomplete-patterns
collect a [i,j] = sum ( fmap (\k -> a ! [i, k] * a ! [j, k]) (A.range [j]))
:t collect

pretty $ tabulate [3,3] (collect a)
#+end_src

#+RESULTS:
: collect :: Num a => Array a -> [Int] -> a
: [[0,0,7],
:  [0,9,46],
:  [0,18,85]]




 #+begin_src haskell-ng :results output
 e = expand (*) a a
 e' = diag $ extracts [1,3] e
 pretty $ fmap pretty e'
 e'' = join $ asArray $ scanl (+) (konst [3,3] 0) (arrayAs $ A.drop 0 (-1) e')
 e''' = join $ diag $ extracts [0,1] e''
 pretty e'''
 #+end_src

 #+RESULTS:
 #+begin_example
 [[[0,0,0],
  [0,9,18],
  [0,18,36]],[[1,4,7],
  [4,16,28],
  [7,28,49]],[[4,10,16],
  [10,25,40],
  [16,40,64]]]
 [[0,0,0],
  [0,9,18],
  [7,46,85]]
 #+end_example


#+begin_src haskell-ng :results output
a = F.range @[3,3]
e = F.expand (*) a a
F.shape e
ex = F.extracts (F.Dims @[1,3]) e
exd = F.diag ex
exdd = F.dropB (F.Dim @0) (SNat @1) exd
pretty $ fmap pretty e'

-- ex = F.extracts @[1,3] e
-- e' = F.diag $ F.extracts @[1,3] e
-- pretty $ fmap pretty e'
-- e'' = join $ asArray $ scanl (+) (konst [3,3] 0) (arrayAs $ A.drop 0 (-1) e')
-- e''' = join $ diag $ extracts [0,1] e''
-- pretty e'''
-- F.dropB (F.Dim @0) (SNat @1) e'
#+end_src

#+RESULTS:
: [3,3,3,3]
: [[[0,0,0],
:  [0,9,18],
:  [0,18,36]],[[1,4,7],
:  [4,16,28],
:  [7,28,49]],[[4,10,16],
:  [10,25,40],
:  [16,40,64]]]

#+begin_src haskell-ng :results output
:k! Eval (DropDim 0 1 '[3])
#+end_src

#+RESULTS:
: Eval (DropDim 0 1 '[3]) :: [Natural]
: = '[2]

 #+begin_src haskell-ng :results output
 F.shape e
 maps [1] id (join e')
 pretty $ join e'
 #+end_src

 #+RESULTS:
 #+begin_example
 UnsafeArray [3,3,3] [0,0,0,0,9,18,0,18,36,1,4,7,4,16,28,7,28,49,4,10,16,10,25,40,16,40,64]
 [[[0,0,0],
   [0,9,18],
   [0,18,36]],
  [[1,4,7],
   [4,16,28],
   [7,28,49]],
  [[4,10,16],
   [10,25,40],
   [16,40,64]]]
 #+end_example

* cross

#+begin_src haskell-ng :results output

c = F.tabulate (F.cross_ (F.range @[3,3])) :: F.Array [3,3] Int
pretty c
#+end_src

#+RESULTS:
: [[0,0,7],
:  [0,9,46],
:  [0,18,85]]



* Next issue #1 bug

#+begin_src sh :results output
ghc --interactive -isrc
#+end_src

Computes an incorrect result for:

#+begin_src haskell-ng
:set -XDataKinds
:load Harpie.Fixed
import Harpie.Fixed as F
import Harpie.Shape as S
a = F.range @[2,3,4]
x1 = indexes (Dims @'[0]) (S.fins @'[2] [0]) a
print (F.index x1 (UnsafeFins [0,1]))
#+end_src

but

#+begin_src sh :results output
ghc --interactive -package-db /Users/tonyday567/haskell/harpie/dist-newstyle/build/aarch64-osx/ghc-9.12.2/harpie-0.1.3.0/package.conf.inplace
#+end_src

is fine.

Reproduced using runhaskell:

#+begin_src sh :results output
runhaskell test/bug-issue1.hs
#+end_src

#+RESULTS:
: 1

#+begin_src sh :results output
runhaskell --ghc-arg='-isrc' test/bug-issue1.hs
#+end_src

#+RESULTS:
: 4

** package-db version (ok)

#+begin_src sh :results output
ghc --interactive -package-db /Users/tonyday567/haskell/harpie/dist-newstyle/build/aarch64-osx/ghc-9.12.2/harpie-0.1.3.0/package.conf.inplace
#+end_src

#+begin_src haskell-ng
:set -XDataKinds
:load Harpie.Fixed
import Harpie.Fixed as F
import Harpie.Shape as S
a = F.range @[2,3,4]
x1 = indexes (Dims @'[0]) (S.fins @'[2] [0]) a
print (F.index x1 (UnsafeFins [0,1]))
#+end_src

1

** -isrc version (bugged)

#+begin_src sh :results output
ghc --interactive -isrc
#+end_src

#+begin_src haskell-ng
:set -XDataKinds
import Harpie.Fixed as F
import Harpie.Shape as S
a = F.range @[2,3,4]
x1 = F.indexes (Dims @'[0]) (S.fins @'[2] [0]) a
print (F.index x1 (UnsafeFins [0,1]))
#+end_src

4

(or segfaults)

** alternatives

- [X] org (not ok)
- [X] cabal repl (not ok)
  #+begin_quote
> cabal repl
Configuration is affected by the following files:
- cabal.project
- cabal.project.local
Build profile: -w ghc-9.12.2 -O1
In order, the following will be built (use -v for more details):
 - harpie-0.1.3.0 (interactive) (lib) (first run)
Preprocessing library for harpie-0.1.3.0...
GHCi, version 9.12.2: https://www.haskell.org/ghc/  :? for help
<no location info>: warning: [GHC-32850] [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules for ‘harpie-0.1.3.0-inplace’ :
        Harpie.Array Harpie.Shape Harpie.Sort

[1 of 4] Compiling Harpie.Shape     ( src/Harpie/Shape.hs, interpreted )
[2 of 4] Compiling Harpie.Sort      ( src/Harpie/Sort.hs, interpreted )
[3 of 4] Compiling Harpie.Array     ( src/Harpie/Array.hs, interpreted )
[4 of 4] Compiling Harpie.Fixed     ( src/Harpie/Fixed.hs, interpreted )
Ok, four modules loaded.
4
Loaded GHCi configuration from /Users/tonyday567/haskell/harpie/.ghci
[1 of 4] Compiling Harpie.Shape     ( src/Harpie/Shape.hs, interpreted )
[2 of 4] Compiling Harpie.Sort      ( src/Harpie/Sort.hs, interpreted )
[3 of 4] Compiling Harpie.Array     ( src/Harpie/Array.hs, interpreted )
[4 of 4] Compiling Harpie.Fixed     ( src/Harpie/Fixed.hs, interpreted )
Ok, four modules loaded.
#+end_quote
- [X] stack ghci (not ok)
- [X] docspec (ok)
- [X] runhaskell can reproduce the error

  #+begin_src sh
  harpie git:(color) ✗ runhaskell bug.hs
1
➜  harpie git:(color) ✗ runhaskell bug.hs
1
➜  harpie git:(color) ✗ runhaskell bug.hs
1
➜  harpie git:(color) ✗ runhaskell --ghc-arg='-isrc' bug.hs
[1]    32322 bus error  runhaskell --ghc-arg='-isrc' bug.hs
➜  harpie git:(color) ✗ runhaskell --ghc-arg='-isrc' bug.hs
[1]    32459 bus error  runhaskell --ghc-arg='-isrc' bug.hs
➜  harpie git:(color) ✗ runhaskell --ghc-arg='-isrc' bug.hs
[1]    32596 bus error  runhaskell --ghc-arg='-isrc' bug.hs
➜  harpie git:(color) ✗ runhaskell --ghc-arg='-isrc' bug.hs
4
  #+end_src
- [X] doctest (not ok)

  #+begin_quote
  cabal repl --with-compiler=doctest
Configuration is affected by the following files:
- cabal.project
- cabal.project.local
Build profile: -w ghc-9.12.2 -O1
In order, the following will be built (use -v for more details):
 - harpie-0.1.3.0 (interactive) (lib) (first run)
Preprocessing library for harpie-0.1.3.0...
Examples: 660  Tried: 65  Errors: 0  Failures: 0
doctest: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.IOException:

user error (Language.Haskell.GhciWrapper.close: Interpreter exited with an error (ExitFailure (-11)))

While handling user error (Language.Haskell.GhciWrapper.close: Interpreter exited with an error (ExitFailure (-11)))

HasCallStack backtrace:
  throwIO, called at src/Run.hs:150:12 in dctst-0.24.0-b15a444d:Run

Error: [Cabal-7125]
repl failed for harpie-0.1.3.0.
  #+end_quote
