

* harry

[[https://hackage.haskell.org/package/harry][file:https://img.shields.io/hackage/v/harry.svg
]][[https://github.com/tonyday567/harry/actions?query=workflow%3Ahaskell-ci][file:https://github.com/tonyday567/harry/workflows/haskell-ci/badge.svg]]


=harry= is a [hyper-rectangular](https://en.wikipedia.org/wiki/Hyperrectangle) array library written in Haskell.

- Boxed Vectors are used as the array container to enforce immutability, permit lazy expression, allow arbitrary element types and otherwise enjoy full usage of the wider Haskell ecosystem.
- An Array type with a value-level Shape is provided in Harry.Array and an Array type with a type-level Shape is provided in Harry.Fixed. With a few exceptions, the API for both modules is the same.
- A distinguishing feature of the library is that functions are =dimension polymorphic=. Most operators input the dimension or dimensions to be operated on or along.

* Usage

Naming conventions clash with the prelude and with each other, so importing should be qualified.

#+begin_src haskell
import qualified Harry.Array as A
import qualified Harry.Shape as S
import qualified Harry.Fixed as F
#+end_src

* ToDo Design notes

** backpermute

** Start with dynamic

** What are arrays

Boxes of stuff

** ToDo Ergonomic

** ToDo Is it fast?
- maybe
- wrapper around vector streaming
- backpermute a novel lazy-fusion mechanism

** ToDo Type safety
- modelled on GHC.TypeNats
- favours arrays as contiguous memory (and not peanoized artifacts)
- 4.5 on (Justin Le's levels)[https://blog.jle.im/entry/levels-of-type-safety-haskell-lists.html] - Static Type safety but no witnesses or dependent typing ambition.

* Development

#+begin_src haskell-ng :results output
:r
:set -Wno-name-shadowing
:set -Wno-type-defaults
import qualified Harry.Shape as S
import qualified Harry.Fixed as F
import qualified Harry.Array as A
import Prettyprinter
import GHC.TypeNats
import Data.Vector qualified as V
#+end_src

* ToDo cabal repl bug

#+begin_src haskell-ng :results output
cabal repl
Build profile: -w ghc-9.8.2 -O1
In order, the following will be built (use -v for more details):
 - harry-0.1 (lib) (ephemeral targets)
Preprocessing library for harry-0.1..
GHCi, version 9.8.2: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/tonyday567/haskell/harry/.ghci
[1 of 4] Compiling Harry.Shape      ( src/Harry/Shape.hs, interpreted )
[2 of 4] Compiling Harry.Sort       ( src/Harry/Sort.hs, interpreted )
[3 of 4] Compiling Harry.Dynamic    ( src/Harry/Dynamic.hs, interpreted )
[4 of 4] Compiling Harry.Fixed      ( src/Harry/Fixed.hs, interpreted )
Ok, four modules loaded.
ghci> import Harry.Fixed as F
ghci> a = F.range @[2,3,4]
ghci> F.extracts (Dims @'[0]) a
[[0,4,8,12,12,16,20,481112440832,481112440832,123158152609792,Error: cabal: repl failed for harry-0.1. The build process segfaulted (i.e.
SIGSEGV).
#+end_src

#+begin_src haskell-ng :results output
F.indexes (Dims @'[0]) (UnsafeFins [0]) a
#+end_src
#+begin_src haskell-ng :results output
c = diag <$> (F.extracts (Dims @[0,1,4,5]) $ F.expand (,) (F.indices @[2,3,4]) (F.indices @[4,3,2]))
ghci> c ! [1,2,2,1]
[([1,2,0],[0,2,1]),([1,2,1],[1,2,1]),([1,2,2],[2,2,1]),([1,2,3],[3,2,1])]
#+end_src
